#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Reachability audit for spawn-orchestrator.sh's 29 subcommands.

Answers, per subcommand, the three questions that decide whether it can be
ported off bash (see dev_docs/orchestrator-python-port.md):

  1. in-process  — is its bash function called directly by another function,
                   bypassing the CLI dispatch table entirely?
  2. launchd     — does the launch script generated by write_launch invoke it,
                   under launchd's pinned minimal PATH?
  3. jail        — does the jailed run-phase agent invoke it from inside
                   sandbox-exec, bound by the profile's process-exec allowlist?

The in-process walk is the one that must be mechanical: the original tier
boundary was wrong because it was reasoned from the dispatch table, which shows
only CLI entry, not the calls functions make to each other.

Usage:  scripts/audit-orchestrator-reachability.py [--json]
Exit:   0 always (this is a report, not a gate).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ORCH = ROOT / "scripts" / "spawn-orchestrator.sh"
SKILLS = ROOT / "skills"

DEF_RE = re.compile(r"^([a-z_][a-z0-9_]*)\(\)\s*\{")
DISPATCH_RE = re.compile(r"^\s{2}([a-z][a-z0-9-]*)\)\s+([a-z_][a-z0-9_]*)\s+\"\$@\"")

# The one input this audit cannot derive mechanically: which call sites in the
# skill docs are executed by the **run-phase agent, inside sandbox-exec**, as
# opposed to an attended phase (launch, --resume, a human at a terminal). Read
# off the docs, with citations, and seeded into the closure below. Everything
# else about the tiers is computed.
JAIL_SEEDS: dict[str, str] = {
    "doctor": "skills/auto-pilot/SKILL.md:337 — top of every run-loop iteration",
    "assert-run-head": "skills/auto-pilot/references/run-state.md:359 — each run-loop iteration",
    "heartbeat": "skills/auto-pilot/SKILL.md:331 — every iteration + deliver-task sub-step",
    "exit-reason": "skills/auto-pilot/SKILL.md:329 — the exit contract, every termination",
    "verify-request": "skills/deliver-task/SKILL.md:143 — the jailed verify handshake",
    "verify-await": "skills/deliver-task/SKILL.md:144 — the jailed verify handshake",
    "alarm-request": "skills/auto-pilot/references/run-budget.md:311 — 'pending in-jail alarm-request'",
}


def load_lines() -> list[str]:
    return ORCH.read_text().splitlines()


def function_spans(lines: list[str]) -> dict[str, tuple[int, int]]:
    """Map function name -> (first line, last line), 1-indexed inclusive.

    Top-level defs only (column 0), which is every function in this file. A
    function runs until the next top-level def, or to the dispatch case.
    """
    starts: list[tuple[int, str]] = []
    for i, line in enumerate(lines, 1):
        m = DEF_RE.match(line)
        if m:
            starts.append((i, m.group(1)))
    spans: dict[str, tuple[int, int]] = {}
    for idx, (start, name) in enumerate(starts):
        end = starts[idx + 1][0] - 1 if idx + 1 < len(starts) else len(lines)
        spans[name] = (start, end)
    return spans


def dispatch_table(lines: list[str]) -> dict[str, str]:
    """Map subcommand -> handler function, from the trailing `case "$sub"`."""
    table: dict[str, str] = {}
    for line in lines:
        m = DISPATCH_RE.match(line)
        if m:
            table[m.group(1)] = m.group(2)
    return table


def enclosing(spans: dict[str, tuple[int, int]], lineno: int) -> str:
    for name, (start, end) in spans.items():
        if start <= lineno <= end:
            return name
    return "<toplevel>"


def in_process_callers(
    lines: list[str], spans: dict[str, tuple[int, int]], fn: str, dispatch_start: int
) -> list[tuple[str, int]]:
    """Every call to `fn` that is neither its own body nor its dispatch entry.

    Only **command position** counts: the name must open a command — at the start
    of a line, inside `$(` / backticks, or after a `;`, `|`, `&&`, `||`, `(`, `{`,
    `if`, `then`, `else`, `do`, `!`. A bare word match is not enough, because
    `status`, `launch`, and `alarm` are also ordinary English and, worse, real
    subcommands of other tools (`git status --porcelain` is all over this file).

    Excluded: the function's own body (recursion is not an external caller), the
    trailing dispatch `case`, and comments.
    """
    opener = r"(?:^|\$\(|`|[;|&({]|\|\||&&|\bif\b|\bthen\b|\belse\b|\bdo\b|!)"
    call = re.compile(rf"{opener}\s*{re.escape(fn)}(?=\s|$|\)|;)")
    own_start, own_end = spans[fn]
    hits: list[tuple[str, int]] = []
    for i, line in enumerate(lines, 1):
        if own_start <= i <= own_end or i >= dispatch_start:
            continue
        code = re.sub(r"(?<!\\)#.*$", "", line)
        if not code.strip():
            continue
        if call.search(code):
            hits.append((enclosing(spans, i), i))
    return hits


def launchd_calls(
    lines: list[str], spans: dict[str, tuple[int, int]], subs: set[str]
) -> dict[str, tuple[str, int]]:
    """Subcommands the two *generated launchd jobs* invoke.

    Both generators emit their script with `printf`, interpolating `$self` (the
    orchestrator's absolute path) as a `%q`. So a callback looks like
    `printf '%q supervisor-scan --dir %q' "$self" ...` — and `$self` is often on
    a *continuation* line, which is why matching `$self` and the subcommand on
    the same line misses `supervisor-scan`, `supervisor-check`, and `report-tick`.
    Match the printf *format string* instead.

    Two generators, both landing under launchd's pinned minimal PATH:
      write_launch        -> the supervisor wrapper (every wake)
      write_verify_broker -> the un-jailed verify broker job
    """
    fmt = re.compile(r"printf\s+'[^']*?(?:%q|/bin/bash %q)\s+([a-z][a-z0-9-]+)\b")
    found: dict[str, tuple[str, int]] = {}
    for gen in ("write_launch", "write_verify_broker"):
        start, end = spans[gen]
        for i in range(start, end + 1):
            for m in fmt.finditer(lines[i - 1]):
                sub = m.group(1)
                if sub in subs and sub not in found:
                    found[sub] = (gen, i)
    return found


def call_graph(
    lines: list[str], spans: dict[str, tuple[int, int]], dispatch_start: int
) -> dict[str, set[str]]:
    """caller -> {callees}, over *every* function, not just the 29 handlers.

    The helpers matter as much as the handlers: `doctor` reaches `alarm_request`
    only through `_doctor_halt`, and `supervisor_check` reaches `teardown` only
    through `_supervisor_halt`. A graph over handlers alone would miss both.
    """
    graph: dict[str, set[str]] = {fn: set() for fn in spans}
    for callee in spans:
        for caller, _ in in_process_callers(lines, spans, callee, dispatch_start):
            if caller in graph:
                graph[caller].add(callee)
    return graph


def constrained_closure(
    graph: dict[str, set[str]],
    table: dict[str, str],
    launchd: dict[str, tuple[str, int]],
) -> dict[str, str]:
    """Every function reachable from a constrained entry point -> why.

    This is the whole point of the audit. A function is constrained if it is
    invoked from a context that cannot freely resolve a Python interpreter, and
    **constraint is inherited through in-process calls**: `status` is not itself
    on launchd's PATH, but `status_report` calls it as a shell function and
    `status_report` *is* — so deleting `status`'s bash body breaks the wake loop
    just as surely. The original tier boundary was drawn without this step.
    """
    why: dict[str, str] = {}
    queue: list[str] = []
    for sub, (gen, ln) in launchd.items():
        fn = table[sub]
        why[fn] = f"launchd — generated by {gen} (spawn-orchestrator.sh:{ln})"
        queue.append(fn)
    for sub, cite in JAIL_SEEDS.items():
        fn = table[sub]
        if fn not in why:
            why[fn] = f"jail — {cite}"
            queue.append(fn)
    while queue:
        fn = queue.pop()
        for callee in sorted(graph.get(fn, ())):
            if callee not in why:
                why[callee] = f"in-process — called by {fn}(), itself constrained"
                queue.append(callee)
    return why


def skill_calls(subs: set[str]) -> dict[str, list[str]]:
    """Every subcommand invocation the skill docs instruct an agent to make.

    Two forms, and both matter: the qualified `spawn-orchestrator.sh <sub>` and
    the bare backticked `` `<sub> --flag` `` the deliver-task handshake is written
    in (`verify-request --worktree …`) — miss the second and the verify handshake
    reads as unreachable, which it very much is not.

    This over-reports on purpose: it cannot tell whether a given call site runs
    *inside* the jail (the run loop) or in an attended phase (launch, resume).
    That judgment is human and is recorded per-row in
    dev_docs/orchestrator-python-port.md — the script's job is to make sure no
    call site is missed, not to tier it.
    """
    qualified = re.compile(r"spawn-orchestrator\.sh`?\s*\n?\s*([a-z][a-z0-9-]+)")
    bare = re.compile(r"`([a-z][a-z0-9-]+)(?:\s+--[a-z-]+|`)")
    found: dict[str, list[str]] = {}
    for path in sorted(SKILLS.rglob("*.md")):
        text = path.read_text()
        rel = path.relative_to(ROOT)
        for rx in (qualified, bare):
            for m in rx.finditer(text):
                sub = m.group(1)
                if sub not in subs:
                    continue
                site = f"{rel}:{text[: m.start()].count(chr(10)) + 1}"
                sites = found.setdefault(sub, [])
                if site not in sites:
                    sites.append(site)
    for sites in found.values():
        sites.sort(key=lambda s: (s.rsplit(":", 1)[0], int(s.rsplit(":", 1)[1])))
    return found


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    args = ap.parse_args()

    lines = load_lines()
    spans = function_spans(lines)
    table = dispatch_table(lines)
    dispatch_start = min(
        i for i, line in enumerate(lines, 1) if line.startswith('case "$sub" in')
    )
    subs = set(table)
    launchd = launchd_calls(lines, spans, subs)
    skills = skill_calls(subs)
    graph = call_graph(lines, spans, dispatch_start)
    why = constrained_closure(graph, table, launchd)

    report = {}
    for sub, fn in table.items():
        callers = in_process_callers(lines, spans, fn, dispatch_start)
        start, end = spans[fn]
        gen_site = None
        if sub in launchd:
            gen, ln = launchd[sub]
            gen_site = f"{gen} -> scripts/spawn-orchestrator.sh:{ln}"
        report[sub] = {
            "fn": fn,
            "lines": end - start + 1,
            "defined_at": f"scripts/spawn-orchestrator.sh:{start}",
            "tier": "B" if fn in why else "A",
            "constrained_by": why.get(fn),
            "in_process_callers": [f"{c} (:{ln})" for c, ln in callers],
            "launchd": gen_site,
            "skill_sites": skills.get(sub, []),
        }

    if args.json:
        json.dump(report, sys.stdout, indent=2)
        print()
        return 0

    tier_b = [s for s, r in report.items() if r["tier"] == "B"]
    tier_a = [s for s, r in report.items() if r["tier"] == "A"]
    b_lines = sum(report[s]["lines"] for s in tier_b)
    a_lines = sum(report[s]["lines"] for s in tier_a)

    print(f"{len(report)} subcommands\n")
    for sub, r in report.items():
        print(
            f"[{r['tier']}] {sub}  ({r['fn']}, {r['lines']} lines, {r['defined_at']})"
        )
        if r["constrained_by"]:
            print(f"      constrained by:    {r['constrained_by']}")
        for c in r["in_process_callers"]:
            print(f"      in-process caller: {c}")
        if r["launchd"]:
            print(f"      launchd job:       {r['launchd']}")
        for s in r["skill_sites"]:
            print(f"      skill invocation:  {s}")

    print(
        f"\nTier A (free to port): {len(tier_a)} subcommands, {a_lines} handler lines\n"
        f"Tier B (constrained):  {len(tier_b)} subcommands, {b_lines} handler lines\n"
        f"\n  Tier A: {', '.join(tier_a)}\n"
        "\nSkill call sites are printed for every subcommand, including Tier A ones —\n"
        "being named in a skill doc is not itself a constraint (a human or an\n"
        "attended phase may invoke it freely). Only the JAIL_SEEDS sites run inside\n"
        "sandbox-exec. Line counts are the handler function only, not its helpers."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
