#!/usr/bin/env python3
"""Build the Copilot instruction files from the canonical guidance docs.

Copilot code review reads `.github/copilot-instructions.md` and the path-scoped
`.github/instructions/*.instructions.md` files, and it does NOT follow links.
This repo's guidance is deliberately link-first (see "Progressive disclosure is
the house style" in AGENTS.md), so a reviewer that cannot follow a link sees a
map and no territory. The fix is a flat copy — and a copy that nothing checks
is a copy that rots, which is what this script exists to prevent.

Each output file is assembled from spans of AGENTS.md and CONTRIBUTING.md
marked with

    <!-- copilot:begin id=some-id -->
    ...
    <!-- copilot:end -->

so the rule keeps exactly one home. Edit the rule where it lives, regenerate,
and commit both. `--check` regenerates in memory and fails if the committed
output disagrees; scripts/check.sh runs it, so drift fails the gate rather than
reaching a reviewer.

Usage:
    python3 scripts/build-copilot-instructions.py            # write the files
    python3 scripts/build-copilot-instructions.py --check    # fail on drift
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import NamedTuple, NoReturn

ROOT = Path(__file__).resolve().parent.parent

# GitHub's own guidance: past ~1000 lines instructions start getting dropped,
# and it recommends trimming anything past ~4000 characters. The line cap is a
# hard failure because a silently-ignored instruction file is indistinguishable
# from one that works.
MAX_LINES = 1000

BEGIN = re.compile(r"<!--\s*copilot:begin\s+id=([A-Za-z0-9_-]+)\s*-->")
END = re.compile(r"<!--\s*copilot:end\s*-->")
INLINE_LINK = re.compile(r"\[([^\]]+)\]\([^)]*\)")
AUTOLINK = re.compile(r"<(https?://[^>]*)>")
BARE_URL = re.compile(r"https?://")

SOURCES = ("AGENTS.md", "CONTRIBUTING.md")


class Output(NamedTuple):
    """One generated file: where it goes, what it covers, what it is made of."""

    path: str
    apply_to: str | None  # the `applyTo` glob; None for the repo-wide file
    title: str
    blocks: tuple[str, ...]


OUTPUTS = (
    Output(
        path=".github/copilot-instructions.md",
        apply_to=None,
        title="Reviewing changes to workflow-skills",
        blocks=(
            "repo-shape",
            "rules-that-bite",
            "working-style-code",
            "merge-status",
        ),
    ),
    Output(
        path=".github/instructions/runtime-prompts.instructions.md",
        apply_to="skills/**,commands/**,agents/**",
        title="Runtime prompt text (skills, commands, handlers, subagents)",
        blocks=(
            "progressive-disclosure",
            "runtime-vs-contributor",
            "logic-typed-file",
            "logic-typed-where",
            "logic-typed-inline",
            "adding-a-skill",
        ),
    ),
    Output(
        path=".github/instructions/shell.instructions.md",
        apply_to="**/*.sh,**/*.bash,**/*.bats",
        title="Shell and test-harness conventions",
        blocks=("shell-conventions",),
    ),
)

HEADER = (
    "<!-- Generated by scripts/build-copilot-instructions.py from {sources}. -->\n"
    "<!-- Do not edit by hand: edit the marked span in the source, then rerun the script. -->"
)


def fail(msg: str) -> NoReturn:
    print(f"build-copilot-instructions.py: {msg}", file=sys.stderr)
    sys.exit(1)


def read_blocks() -> dict[str, tuple[str, str]]:
    """Return {id: (source file, body)} for every marked span in SOURCES."""
    blocks: dict[str, tuple[str, str]] = {}
    for name in SOURCES:
        lines = (ROOT / name).read_text().splitlines()
        open_id: str | None = None
        body: list[str] = []
        for lineno, line in enumerate(lines, 1):
            begin = BEGIN.search(line)
            if begin:
                if open_id:
                    fail(f"{name}:{lineno}: copilot:begin inside block {open_id!r}")
                open_id = begin.group(1)
                body = []
                continue
            if END.search(line):
                if not open_id:
                    fail(f"{name}:{lineno}: copilot:end with no open block")
                if open_id in blocks:
                    fail(f"{name}:{lineno}: duplicate block id {open_id!r}")
                blocks[open_id] = (name, "\n".join(body).strip("\n"))
                open_id = None
                continue
            if open_id is not None:
                body.append(line)
        if open_id:
            fail(f"{name}: block {open_id!r} is never closed")
    return blocks


def flatten_links(text: str, where: str) -> str:
    """Strip markdown link syntax — Copilot ignores links, so leave only prose."""
    text = INLINE_LINK.sub(r"\1", text)
    text = AUTOLINK.sub("", text)
    if BARE_URL.search(text):
        fail(
            f"{where}: a bare URL survives in a marked block; Copilot cannot follow it"
        )
    return text


def render(spec: Output, blocks: dict[str, tuple[str, str]]) -> str:
    parts: list[str] = []
    if spec.apply_to:
        parts.append(f'---\napplyTo: "{spec.apply_to}"\n---')
    used: list[str] = []
    bodies: list[str] = []
    for block_id in spec.blocks:
        if block_id not in blocks:
            fail(
                f"{spec.path}: no block marked id={block_id} in {' or '.join(SOURCES)}"
            )
        source, body = blocks[block_id]
        used.append(source)
        bodies.append(flatten_links(body, f"{source} (id={block_id})"))
    sources = ", ".join(dict.fromkeys(used))
    parts.append(HEADER.format(sources=sources))
    parts.append(f"# {spec.title}")
    parts.extend(bodies)
    return "\n\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if a committed file differs from what this script would write",
    )
    args = parser.parse_args()

    blocks = read_blocks()
    unused = set(blocks) - {b for spec in OUTPUTS for b in spec.blocks}
    if unused:
        fail(f"marked but unused block ids: {', '.join(sorted(unused))}")

    stale: list[str] = []
    for spec in OUTPUTS:
        path = ROOT / spec.path
        content = render(spec, blocks)
        line_count = content.count("\n")
        if line_count > MAX_LINES:
            fail(
                f"{spec.path}: {line_count} lines exceeds Copilot's ~{MAX_LINES}-line ceiling"
            )
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(spec.path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    if stale:
        print(
            "build-copilot-instructions.py: out of date: "
            + ", ".join(stale)
            + "\n  the guidance in AGENTS.md/CONTRIBUTING.md has moved on; regenerate with:"
            + "\n    python3 scripts/build-copilot-instructions.py",
            file=sys.stderr,
        )
        return 1
    print(f"build-copilot-instructions.py: OK ({len(OUTPUTS)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
